typography_spectrum: 0.8677793093957007
color:
  brandStrength: 0.993765298044309
  lightness: 0.7162956290412694
  saturation: 0.0422260407358408
  rhythmicContrast: 0.4429595093242824
  brandColors:
    - '#FFFFFF'
    - '#424242'
    - '#ED4846'
    - '#DADADA'
    - '#A8A8A8'
layout_spectrum: 0.5406442021485418
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5fcb5ca5-f2bc-4d45-be75-6152a1417d90.png
name: The Doctor
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5f2a5036-d3fb-45fc-aeb5-5d00c2eddc14.png
title: Your Doctor. Completely Reinvented.
description: We didn't change anything. We changed everything!
